### ISSUE TITLE
Add a Toggle b/w light and Dark mode

### ISSUE THREAD

**Issue by shamvi-05** [shamvi-05/MLH_Orientation_Hackathon#1]
A toggle can be created beside the navbar for better User Experience

**Comment by shamvi-05** [comment]
@V2dha @ssurbhi560 if you folks can work on this?
I am trying but facing some issues keeping in mind the deadline so just wanted to let you all know the progress.

**Comment by ssurbhi560** [comment]
I am taking this up!
