### ISSUE TITLE
Use GitHub Actions for automating deployment.

### ISSUE THREAD

**Issue by ssurbhi560** [shamvi-05/MLH_Orientation_Hackathon#4]
We should use GitHub Actions for automating the deployment. So, every time a PR is merged changes will be applied in the deployment on its own.

**Comment by V2dha** [comment]
I guess in the case of GitHub pages also any changes done on the main branch are reflected back on deployed site.

**Comment by ssurbhi560** [comment]
Okay, then I am closing this one.
