### ISSUE TITLE
Add a ChatBot Assistant

### ISSUE THREAD

**Issue by shamvi-05** [shamvi-05/MLH_Orientation_Hackathon#7]
UserExperience can be shared and Queries can be solved.
Using Tidio chatbot [Refer this](https://www.tidio.com/lp/chatbots/?utm_source=google.com&utm_medium=cpc&utm_campaign=16725204475&utm_content=590413057602&utm_term=tidio%20chatbot&a_bucket=sem&a_type=brand&a_source=google.com&a_v=2&a_g_campaignid=16725204475&a_g_keyword=tidio%20chatbot&a_g_adgroupid=143580668828&a_g_creative=590413057602&gclid=Cj0KCQjwheyUBhD-ARIsAHJNM-PiWl6pV5Ov7meohodB9B1hSuMeTxv-pBoWjfcoG7uExDlXLE6AV7waAv9xEALw_wcB)

**Comment by shamvi-05** [comment]
![Screen Shot 2022-06-04 at 7 38 42 PM](https://user-images.githubusercontent.com/78691639/172005982-ce749335-3e78-4483-b4f4-c9befcd73dca.png)
After adding it looks like this Should I integrate it? @V2dha @ssurbhi560 
When not triggered it will be displayed like this
![Screen Shot 2022-06-04 at 7 49 46 PM](https://user-images.githubusercontent.com/78691639/172006236-046f8abb-91d2-44bc-97b4-14f0e63a057d.png)

**Comment by V2dha** [comment]
Yes, it seems good! You can integrate it.
Also make sure to pull the changes first as I just merged the team members' info into the main, to avoid any merge conflicts.
